apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-webhook-cert
  namespace: security
spec:
  secretName: webhook-server-cert
  duration: 8760h # 1 year
  renewBefore: 360h # 15 days before expiry
  dnsNames:
    - vault-config-operator-webhook-service.security.svc.cluster.local
    - vault-config-operator-webhook-service.security
    - vault-config-operator-webhook-service.security.svc
  issuerRef:
    name: vault-webhook-issuer
    kind: Issuer
