apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-webhook-cert
  namespace: security
spec:
  secretName: vault-config-operator-webhook-service-cert
  duration: 8760h # 1 year
  renewBefore: 360h # 15 days before expiry
  subject:
    organizations:
      - vault-config-operator
  commonName: vault-config-operator-webhook-service.security.svc
  dnsNames:
    - vault-config-operator-webhook-service.security.svc
    - vault-config-operator-webhook-service.security.svc.cluster.local
  issuerRef:
    name: vault-ca-issuer  # Change to your actual issuer name
    kind: ClusterIssuer    # Or "Issuer" if using namespace-scoped issuer
