apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-metrics-cert
  namespace: security
spec:
  secretName: vault-config-operator-metrics-service-cert
  duration: 8760h
  renewBefore: 360h
  subject:
    organizations:
      - vault-config-operator
  commonName: vault-config-operator-controller-manager-metrics-service.security.svc
  dnsNames:
    - vault-config-operator-controller-manager-metrics-service.security.svc
    - vault-config-operator-controller-manager-metrics-service.security.svc.cluster.local
  issuerRef:
    name: vault-ca-issuer
    kind: ClusterIssuer
