apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-metrics-cert
  namespace: security
spec:
  secretName: vault-config-operator-certs
  duration: 8760h
  renewBefore: 360h
  dnsNames:
    - vault-metrics.security.svc
    - vault-metrics.security
    - vault-metrics.security.svc.cluster.local
  issuerRef:
    name: vault-metrics-issuer
    kind: Issuer